server:
  servlet:
    context-path: /divertfest/api

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:divertfestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

springdoc:
  swagger-ui:
    path: /swagger