server:
  servlet:
    context-path: /divertfest/api

spring:
  config:
    import: classpath:application-env.properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: divertfest
  config:
    import: classpath:application-env.properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: divertfest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASS}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 15
      maximumPoolSize: 50
      connectionTimeout: 30000
      idleTimeout: 30000
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASS}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 15
      maximumPoolSize: 50
      connectionTimeout: 30000
      idleTimeout: 30000

springdoc:
  swagger-ui:
    path: /swagger

logging:
  level:
    com.divertech: ${LOG_LEVEL}

logging:
  level:
    com.divertech: ${LOG_LEVEL}

divertfest:
  jwt:
    expiracao: ${JWT_TEMPO_EXPIRACAO}
    chave: ${JWT_CHAVE}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

aws:
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

